displayName=Wyrmscraig Golem Tracker
author=Nobody
description=Shows the estimated golems needed for your next Crafting level
tags=crafting,golems,wyrmscraig
version=
plugins=com.wyrmscraiggolemtracker.WyrmscraigGolemTrackerPlugin
build=standard
